### ISSUE TITLE
Ticket prioritisation content update

### ISSUE THREAD

**Issue by Kalaiselvan88** [axelerant/engg-handbook#187]
This ticket is to work on the comments as mentioned [here](https://github.com/axelerant/engg-handbook/pull/164#issuecomment-2114075237) once this [PR](https://github.com/axelerant/engg-handbook/pull/164) is merged

**Comment by Yemaneberhan-Lemma** [comment]
@Kalaiselvan88: Can you close this issue since PR was merged and [content is now available in the engineering handbook?](https://engg-handbook.axelerant.com/docs/productivity/prioritizing-tasks/)
