### ISSUE TITLE
Content on Incident Management and root cause analysis

### ISSUE THREAD

**Issue by Kalaiselvan88** [axelerant/engg-handbook#206]
Initially we did not pick up this as it was CDM specific however I feel irrespective of the Program RCA can be done for any projects. 

Hence this ticket.

To give more context, [as part of this course in Thinkfic](https://learning.axelerant.com/courses/take/cdm-estimation-process/texts/32442060-incident-management-in-cdm) we talk about

1. Proactive, Corrective and Reactive actions for any issues that happen on Production
2. RCA template (current one - https://learning.axelerant.com/courses/take/cdm-estimation-process/texts/32442516-root-cause-analysis-rca-template)
3. Pre-approved hours usage for handling incidents.

I can contribute to above and create a 1st draft if it is ok to include this in the Engineering Handbook. If so, kindly share where this can go in the engineering handbook. Under https://engg-handbook.axelerant.com/docs/common-areas/ ?

**Comment by hussainweb** [comment]
I'd say that this makes more sense under the How We Work section. It sounds like this is targeted content based on how we work and that is why I think this is beyond the common areas of concern.

**Comment by Kalaiselvan88** [comment]
> I'd say that this makes more sense under the How We Work section. It sounds like this is targeted content based on how we work and that is why I think this is beyond the common areas of concern.

Yes. I also thought of How we work as well. I will create a PR for review

**Comment by Kalaiselvan88** [comment]
Raised https://github.com/axelerant/engg-handbook/pulls

**Comment by hussainweb** [comment]
Let's keep this open since the PR is still open.
