### ISSUE TITLE
Links are not working in the common areas of concern in web projects index page

### ISSUE THREAD

**Issue by Yemaneberhan-Lemma** [axelerant/engg-handbook#39]
Links in the common areas of concern in web projects index page are not working.

**Comment by hussainweb** [comment]
The problem is elsewhere. I didn't really need #42 but it doesn't hurt either.

**Comment by hussainweb** [comment]
@Yemaneberhan-Lemma, please see the fix in https://github.com/axelerant/engg-handbook/commit/85b101ef170044e2548de819bf4f2c109650fcad. We should use `relref` whenever we need to output links. See https://gohugo.io/functions/relref/
