### ISSUE TITLE
Typo in Boring Tech section

### ISSUE THREAD

**Issue by axelerant-hardik** [axelerant/engg-handbook#82]
There is a typo I encountered while reading through the Engineering Handbook's [Boring Tech](https://axelerant.github.io/engg-handbook/docs/principles/engineering-focus/#boring-tech) section.

The sections says _But if our choice of technology stops use from solving a problem_ , but I guess it should be _But if our choice of technology stops **us** from solving a problem_

**Comment by hussainweb** [comment]
Thanks! Good find. Do you want to create a PR for this?

**Comment by Yemaneberhan-Lemma** [comment]
For the moment, I already created PR for this.
